project 'Generic Structure.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Generic Structure' do
    pod 'Alamofire', '~> 4.5'
    pod 'Gloss', '~> 2.0'
end
